// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 14.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace CodedUITestProject1
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.HtmlControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public partial class UIMap
    {
        
        /// <summary>
        /// RecordedMethod1 - Use 'RecordedMethod1Params' to pass parameters into this method.
        /// </summary>
        public void RecordedMethod1()
        {
            #region Variable Declarations
            HtmlHyperlink uIAboutHyperlink = this.UIHomePageMyASPNETApplWindow.UIHomePageMyASPNETApplDocument.UIAboutHyperlink;
            HtmlHyperlink uIContactHyperlink = this.UIHomePageMyASPNETApplWindow.UIAboutMyASPNETApplicaDocument.UIContactHyperlink;
            HtmlHyperlink uIHomeHyperlink = this.UIHomePageMyASPNETApplWindow.UIContactMyASPNETAppliDocument.UIHomeHyperlink;
            HtmlEdit uIPvmEdit = this.UIHomePageMyASPNETApplWindow.UIHomePageMyASPNETApplDocument.UIPvmEdit;
            HtmlInputButton uILähetäButton = this.UIHomePageMyASPNETApplWindow.UIHomePageMyASPNETApplDocument.UILähetäButton;
            #endregion

            // Click 'About' link
            Mouse.Click(uIAboutHyperlink, new Point(35, 33));

            // Click 'Contact' link
            Mouse.Click(uIContactHyperlink, new Point(44, 32));

            // Click 'Home' link
            Mouse.Click(uIHomeHyperlink, new Point(60, 32));

            // Type '26.4.2016' in 'pvm' text box
            uIPvmEdit.Text = this.RecordedMethod1Params.UIPvmEditText;

            // Click 'Lähetä' button
            Mouse.Click(uILähetäButton, new Point(49, 14));
        }
        
        #region Properties
        public virtual RecordedMethod1Params RecordedMethod1Params
        {
            get
            {
                if ((this.mRecordedMethod1Params == null))
                {
                    this.mRecordedMethod1Params = new RecordedMethod1Params();
                }
                return this.mRecordedMethod1Params;
            }
        }
        
        public UIHomePageMyASPNETApplWindow UIHomePageMyASPNETApplWindow
        {
            get
            {
                if ((this.mUIHomePageMyASPNETApplWindow == null))
                {
                    this.mUIHomePageMyASPNETApplWindow = new UIHomePageMyASPNETApplWindow();
                }
                return this.mUIHomePageMyASPNETApplWindow;
            }
        }
        #endregion
        
        #region Fields
        private RecordedMethod1Params mRecordedMethod1Params;
        
        private UIHomePageMyASPNETApplWindow mUIHomePageMyASPNETApplWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'RecordedMethod1'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class RecordedMethod1Params
    {
        
        #region Fields
        /// <summary>
        /// Type '26.4.2016' in 'pvm' text box
        /// </summary>
        public string UIPvmEditText = "26.4.2016";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIHomePageMyASPNETApplWindow : BrowserWindow
    {
        
        public UIHomePageMyASPNETApplWindow()
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "Home Page - My ASP.NET Application";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("Home Page - My ASP.NET Application");
            this.WindowTitles.Add("About - My ASP.NET Application");
            this.WindowTitles.Add("Contact - My ASP.NET Application");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UIHomePageMyASPNETApplDocument UIHomePageMyASPNETApplDocument
        {
            get
            {
                if ((this.mUIHomePageMyASPNETApplDocument == null))
                {
                    this.mUIHomePageMyASPNETApplDocument = new UIHomePageMyASPNETApplDocument(this);
                }
                return this.mUIHomePageMyASPNETApplDocument;
            }
        }
        
        public UIAboutMyASPNETApplicaDocument UIAboutMyASPNETApplicaDocument
        {
            get
            {
                if ((this.mUIAboutMyASPNETApplicaDocument == null))
                {
                    this.mUIAboutMyASPNETApplicaDocument = new UIAboutMyASPNETApplicaDocument(this);
                }
                return this.mUIAboutMyASPNETApplicaDocument;
            }
        }
        
        public UIContactMyASPNETAppliDocument UIContactMyASPNETAppliDocument
        {
            get
            {
                if ((this.mUIContactMyASPNETAppliDocument == null))
                {
                    this.mUIContactMyASPNETAppliDocument = new UIContactMyASPNETAppliDocument(this);
                }
                return this.mUIContactMyASPNETAppliDocument;
            }
        }
        #endregion
        
        #region Fields
        private UIHomePageMyASPNETApplDocument mUIHomePageMyASPNETApplDocument;
        
        private UIAboutMyASPNETApplicaDocument mUIAboutMyASPNETApplicaDocument;
        
        private UIContactMyASPNETAppliDocument mUIContactMyASPNETAppliDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIHomePageMyASPNETApplDocument : HtmlDocument
    {
        
        public UIHomePageMyASPNETApplDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Home Page - My ASP.NET Application";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://localhost:2440/";
            this.WindowTitles.Add("Home Page - My ASP.NET Application");
            #endregion
        }
        
        #region Properties
        public HtmlHyperlink UIAboutHyperlink
        {
            get
            {
                if ((this.mUIAboutHyperlink == null))
                {
                    this.mUIAboutHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUIAboutHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUIAboutHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUIAboutHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUIAboutHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "About";
                    this.mUIAboutHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/Home/About";
                    this.mUIAboutHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUIAboutHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "http://localhost:2440/Home/About";
                    this.mUIAboutHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = null;
                    this.mUIAboutHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "href=\"/Home/About\"";
                    this.mUIAboutHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "3";
                    this.mUIAboutHyperlink.WindowTitles.Add("Home Page - My ASP.NET Application");
                    #endregion
                }
                return this.mUIAboutHyperlink;
            }
        }
        
        public HtmlEdit UIPvmEdit
        {
            get
            {
                if ((this.mUIPvmEdit == null))
                {
                    this.mUIPvmEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUIPvmEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = null;
                    this.mUIPvmEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "pvm";
                    this.mUIPvmEdit.SearchProperties[HtmlEdit.PropertyNames.LabeledBy] = null;
                    this.mUIPvmEdit.SearchProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUIPvmEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUIPvmEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = null;
                    this.mUIPvmEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"pvm\" type=\"text\"";
                    this.mUIPvmEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "1";
                    this.mUIPvmEdit.WindowTitles.Add("Home Page - My ASP.NET Application");
                    #endregion
                }
                return this.mUIPvmEdit;
            }
        }
        
        public HtmlInputButton UILähetäButton
        {
            get
            {
                if ((this.mUILähetäButton == null))
                {
                    this.mUILähetäButton = new HtmlInputButton(this);
                    #region Search Criteria
                    this.mUILähetäButton.SearchProperties[HtmlButton.PropertyNames.Id] = "Submit1";
                    this.mUILähetäButton.SearchProperties[HtmlButton.PropertyNames.Name] = null;
                    this.mUILähetäButton.SearchProperties[HtmlButton.PropertyNames.DisplayText] = "Lähetä";
                    this.mUILähetäButton.SearchProperties[HtmlButton.PropertyNames.Type] = "submit";
                    this.mUILähetäButton.FilterProperties[HtmlButton.PropertyNames.Title] = null;
                    this.mUILähetäButton.FilterProperties[HtmlButton.PropertyNames.Class] = null;
                    this.mUILähetäButton.FilterProperties[HtmlButton.PropertyNames.ControlDefinition] = "id=\"Submit1\" type=\"submit\" value=\"Lähetä";
                    this.mUILähetäButton.FilterProperties[HtmlButton.PropertyNames.TagInstance] = "2";
                    this.mUILähetäButton.WindowTitles.Add("Home Page - My ASP.NET Application");
                    #endregion
                }
                return this.mUILähetäButton;
            }
        }
        #endregion
        
        #region Fields
        private HtmlHyperlink mUIAboutHyperlink;
        
        private HtmlEdit mUIPvmEdit;
        
        private HtmlInputButton mUILähetäButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIAboutMyASPNETApplicaDocument : HtmlDocument
    {
        
        public UIAboutMyASPNETApplicaDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "About - My ASP.NET Application";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/Home/About";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://localhost:2440/Home/About";
            this.WindowTitles.Add("About - My ASP.NET Application");
            #endregion
        }
        
        #region Properties
        public HtmlHyperlink UIContactHyperlink
        {
            get
            {
                if ((this.mUIContactHyperlink == null))
                {
                    this.mUIContactHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUIContactHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUIContactHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUIContactHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUIContactHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Contact";
                    this.mUIContactHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/Home/Contact";
                    this.mUIContactHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUIContactHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "http://localhost:2440/Home/Contact";
                    this.mUIContactHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = null;
                    this.mUIContactHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "href=\"/Home/Contact\"";
                    this.mUIContactHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "4";
                    this.mUIContactHyperlink.WindowTitles.Add("About - My ASP.NET Application");
                    #endregion
                }
                return this.mUIContactHyperlink;
            }
        }
        #endregion
        
        #region Fields
        private HtmlHyperlink mUIContactHyperlink;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIContactMyASPNETAppliDocument : HtmlDocument
    {
        
        public UIContactMyASPNETAppliDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Contact - My ASP.NET Application";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/Home/Contact";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://localhost:2440/Home/Contact";
            this.WindowTitles.Add("Contact - My ASP.NET Application");
            #endregion
        }
        
        #region Properties
        public HtmlHyperlink UIHomeHyperlink
        {
            get
            {
                if ((this.mUIHomeHyperlink == null))
                {
                    this.mUIHomeHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUIHomeHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUIHomeHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUIHomeHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUIHomeHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Home";
                    this.mUIHomeHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/";
                    this.mUIHomeHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUIHomeHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "http://localhost:2440/";
                    this.mUIHomeHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = null;
                    this.mUIHomeHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "href=\"/\"";
                    this.mUIHomeHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "2";
                    this.mUIHomeHyperlink.WindowTitles.Add("Contact - My ASP.NET Application");
                    #endregion
                }
                return this.mUIHomeHyperlink;
            }
        }
        #endregion
        
        #region Fields
        private HtmlHyperlink mUIHomeHyperlink;
        #endregion
    }
}
